from __future__ import annotations

"""Build GT49 YOLO26 segmentation-style visual overlays for manual review.

YOLO26 is a detector, not a segmentation model.  For manual inspection we
therefore render detector-derived proposal masks: each predicted box is
converted into a lightweight edge/dark-region mask inside the box and overlaid
on the native image.  The output is meant for visual scoring of whether a
method exposes road-defect evidence; quantitative tables still use the box
metrics generated by eval_native_tiled_detector.py and eval_gt49_defect_protocol.py.
"""

import argparse
import csv
from pathlib import Path

import cv2
import numpy as np
from PIL import Image, ImageDraw, ImageFont


METHODS = [
    "raw",
    "rmr_blind",
    "rmr_metadata",
    "rmr_eta_0p25",
    "rmr_metadata_gated",
    "nafnet",
    "dfpir",
    "demoe_auto",
    "demoe_scenario",
    "instructir_generic",
    "instructir_metadata",
]

METHOD_LABELS = {
    "raw": "Raw",
    "rmr_dual_evidence": "RMR-Net dual",
    "rmr_blind": "RMR image",
    "rmr_metadata": "RMR meta",
    "rmr_eta_0p25": "RMR-Net recovery",
    "rmr_metadata_gated": "RMR gate",
    "nafnet": "NAFNet",
    "dfpir": "DFPIR",
    "demoe_auto": "DeMoE auto",
    "demoe_scenario": "DeMoE scen",
    "instructir_generic": "InstructIR",
    "instructir_metadata": "InstructIR meta",
}

CLASS_NAMES = {
    0: "long",
    1: "trans",
    2: "allig",
    3: "pothole",
}

CLASS_COLORS = {
    0: (32, 180, 255),   # longitudinal: orange-blue contrast
    1: (60, 220, 120),   # transverse: green
    2: (255, 120, 80),   # alligator: coral
    3: (220, 80, 255),   # pothole: magenta
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--sets-root",
        type=Path,
        default=Path("experiments/roboflow_geotagged_v5_native_real/v36_yolo26_rdd4_eval_sets"),
    )
    parser.add_argument(
        "--eval-root",
        type=Path,
        default=Path("experiments/roboflow_geotagged_v5_native_real/v38_yolo26_cropmask_eval"),
    )
    parser.add_argument(
        "--eta-sets-root",
        type=Path,
        default=Path("experiments/roboflow_geotagged_v5_native_real/v36_yolo26_rdd4_eta_sets"),
    )
    parser.add_argument(
        "--eta-eval-root",
        type=Path,
        default=Path("experiments/roboflow_geotagged_v5_native_real/v38_yolo26_cropmask_eta_eval"),
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("experiments/roboflow_geotagged_v5_native_real/v38_yolo26_cropmask_visual_overlays"),
    )
    parser.add_argument("--methods", default=",".join(METHODS))
    parser.add_argument("--conf", type=float, default=0.10)
    parser.add_argument("--panel-width", type=int, default=520)
    parser.add_argument("--max-atlas-images", type=int, default=12)
    return parser.parse_args()


def method_root(method: str, base_root: Path, eta_root: Path) -> Path:
    if (base_root / method).exists():
        return base_root / method
    if (eta_root / method).exists():
        return eta_root / method
    if method == "rmr_dual_evidence" and (base_root / "raw").exists():
        # Dual evidence is a detection-level fusion policy, so it renders on
        # the unmodified native image while using the fused prediction CSV.
        return base_root / "raw"
    return base_root / method


def read_predictions(path: Path, conf: float) -> dict[str, list[dict[str, float | int | str]]]:
    preds: dict[str, list[dict[str, float | int | str]]] = {}
    if not path.exists():
        return preds
    with path.open(newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            score = float(row["conf"])
            if score < conf:
                continue
            cls = int(float(row["class_id"]))
            if cls not in CLASS_NAMES:
                continue
            item = {
                "image": row["image"],
                "cls": cls,
                "conf": score,
                "x1": float(row["x1"]),
                "y1": float(row["y1"]),
                "x2": float(row["x2"]),
                "y2": float(row["y2"]),
            }
            preds.setdefault(row["image"], []).append(item)
    return preds


def read_gt(label_path: Path, width: int, height: int) -> list[tuple[int, tuple[float, float, float, float]]]:
    boxes: list[tuple[int, tuple[float, float, float, float]]] = []
    if not label_path.exists():
        return boxes
    for line in label_path.read_text(encoding="utf-8").splitlines():
        parts = line.strip().split()
        if len(parts) < 5:
            continue
        cls = int(float(parts[0]))
        xc, yc, bw, bh = (float(v) for v in parts[1:5])
        boxes.append(
            (
                cls,
                (
                    (xc - bw / 2) * width,
                    (yc - bh / 2) * height,
                    (xc + bw / 2) * width,
                    (yc + bh / 2) * height,
                ),
            )
        )
    # GT49 crop/mask scoring uses the lower-road half.  Show only scored GT
    # boxes in visual overlays so the figure matches the reported metrics.
    return [item for item in boxes if 0.5 * (item[1][1] + item[1][3]) >= height / 2.0]


def proposal_mask(crop_rgb: np.ndarray, cls: int) -> np.ndarray:
    if crop_rgb.size == 0:
        return np.zeros(crop_rgb.shape[:2], dtype=np.uint8)
    gray = cv2.cvtColor(crop_rgb, cv2.COLOR_RGB2GRAY)
    gray = cv2.equalizeHist(gray)
    edges = cv2.Canny(gray, 50, 140)
    kernel = np.ones((3, 3), np.uint8)
    edges = cv2.dilate(edges, kernel, iterations=1)
    if cls == 3:
        # Potholes are region-like: combine edges with locally dark/rough pixels.
        thresh = np.percentile(gray, 42)
        dark = (gray <= thresh).astype(np.uint8) * 255
        mask = cv2.morphologyEx(cv2.bitwise_or(edges, dark), cv2.MORPH_CLOSE, np.ones((7, 7), np.uint8))
    else:
        # Cracks are thin: preserve sparse edge-like evidence.
        mask = cv2.morphologyEx(edges, cv2.MORPH_CLOSE, np.ones((5, 5), np.uint8))
    return mask


def render_method_overlay(
    image_path: Path,
    label_path: Path,
    preds: list[dict[str, float | int | str]],
    method_label: str,
    out_width: int,
) -> Image.Image:
    image = Image.open(image_path).convert("RGB")
    src_w, src_h = image.size
    scale = out_width / src_w
    out_h = int(src_h * scale)
    canvas = image.resize((out_width, out_h), Image.Resampling.LANCZOS)
    arr = np.array(canvas).copy()
    overlay = arr.copy()
    roi_y = out_h // 2

    # Make the YOLO26 crop/mask protocol visible in the qualitative figure.
    # The top half is retained for reader context but dimmed because it is not
    # scored by the lower-road detector.  Predictions are mapped back to native
    # coordinates before this rendering step.
    overlay[:roi_y] = (overlay[:roi_y] * 0.42 + np.array([235, 235, 235]) * 0.58).astype(np.uint8)
    cv2.line(overlay, (0, roi_y), (out_width - 1, roi_y), (255, 70, 70), 3)

    for pred in preds:
        cls = int(pred["cls"])
        x1 = max(0, int(float(pred["x1"]) * scale))
        y1 = max(0, int(float(pred["y1"]) * scale))
        x2 = min(out_width - 1, int(float(pred["x2"]) * scale))
        y2 = min(out_h - 1, int(float(pred["y2"]) * scale))
        if x2 <= x1 or y2 <= y1:
            continue
        crop = arr[y1:y2, x1:x2]
        mask = proposal_mask(crop, cls)
        color = np.array(CLASS_COLORS[cls], dtype=np.uint8)
        region = overlay[y1:y2, x1:x2]
        region[mask > 0] = (0.35 * region[mask > 0] + 0.65 * color).astype(np.uint8)
        overlay[y1:y2, x1:x2] = region
        cv2.rectangle(overlay, (x1, y1), (x2, y2), tuple(int(c) for c in color.tolist()), 2)

    blended = cv2.addWeighted(arr, 0.60, overlay, 0.40, 0)
    panel = Image.fromarray(blended)
    draw = ImageDraw.Draw(panel)
    font = ImageFont.load_default()
    draw.rectangle((0, 0, out_width, 20), fill=(255, 255, 255))
    draw.text((4, 4), method_label, fill=(0, 0, 0), font=font)
    draw.rectangle((0, roi_y - 15, 185, roi_y + 2), fill=(255, 255, 255))
    draw.text((4, roi_y - 13), "YOLO26 ROI scored below", fill=(190, 40, 40), font=font)

    for cls, box in read_gt(label_path, src_w, src_h):
        x1, y1, x2, y2 = [v * scale for v in box]
        draw.rectangle((x1, y1, x2, y2), outline=(255, 214, 10), width=2)
        draw.text((x1, max(20, y1 - 11)), f"GT {CLASS_NAMES.get(cls, cls)}", fill=(255, 214, 10), font=font)

    for pred in preds[:80]:
        cls = int(pred["cls"])
        x1 = float(pred["x1"]) * scale
        y1 = float(pred["y1"]) * scale
        draw.text((x1, max(20, y1)), f"{CLASS_NAMES[cls]} {float(pred['conf']):.2f}", fill=CLASS_COLORS[cls], font=font)
    return panel


def make_comparison(image_name: str, method_panels: list[Image.Image], out_path: Path) -> None:
    gap = 8
    width = sum(p.width for p in method_panels) + gap * (len(method_panels) - 1)
    height = max(p.height for p in method_panels)
    canvas = Image.new("RGB", (width, height), (250, 250, 250))
    x = 0
    for panel in method_panels:
        canvas.paste(panel, (x, 0))
        x += panel.width + gap
    out_path.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(out_path, quality=92)


def main() -> None:
    args = parse_args()
    methods = [m.strip() for m in args.methods.split(",") if m.strip()]
    args.out.mkdir(parents=True, exist_ok=True)

    predictions = {}
    for method in methods:
        eval_dir = method_root(method, args.eval_root, args.eta_eval_root)
        predictions[method] = read_predictions(eval_dir / "predictions.csv", args.conf)
    raw_images = args.sets_root / "raw" / "images" / "test"
    image_names = sorted(p.name for p in raw_images.iterdir() if p.suffix.lower() in {".jpg", ".jpeg", ".png"})

    atlas_panels: list[Image.Image] = []
    for idx, image_name in enumerate(image_names):
        method_panels: list[Image.Image] = []
        for method in methods:
            set_dir = method_root(method, args.sets_root, args.eta_sets_root)
            image_path = set_dir / "images" / "test" / image_name
            label_path = set_dir / "labels" / "test" / f"{Path(image_name).stem}.txt"
            panel = render_method_overlay(
                image_path,
                label_path,
                predictions.get(method, {}).get(image_name, []),
                METHOD_LABELS.get(method, method),
                args.panel_width,
            )
            method_panels.append(panel)
        comparison_path = args.out / "comparison_by_image" / f"{Path(image_name).stem}_yolo26_overlay.jpg"
        make_comparison(image_name, method_panels, comparison_path)
        if idx < args.max_atlas_images:
            atlas_panels.append(Image.open(comparison_path).convert("RGB"))

    if atlas_panels:
        gap = 14
        width = max(p.width for p in atlas_panels)
        height = sum(p.height for p in atlas_panels) + gap * (len(atlas_panels) - 1)
        atlas = Image.new("RGB", (width, height), (255, 255, 255))
        y = 0
        for panel in atlas_panels:
            atlas.paste(panel, (0, y))
            y += panel.height + gap
        atlas.save(args.out / "gt49_yolo26_segmentation_overlay_atlas.jpg", quality=92)
    print(f"Wrote overlays for {len(image_names)} images to {args.out}")


if __name__ == "__main__":
    main()
